### ISSUE TITLE
ikony FB a TW

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#11]
ikony FB a TW nechat je na hlavní stránce (hlavní menu)

**Comment by LenkaKravecova** [comment]
ikonky jsou i na jiných stránkách, prosíme, aby to bylo jen na té hlavní

**Comment by jirkadev** [comment]
ok, vrátil jsem to tam proto, že jsem chtěl aby na každé stránce byla patička. Teď je to tedy tak, že na hlavní stránce jsou ikony a na ostatních stránkách místo patičky 25px volného místa.

**Comment by LenkaKravecova** [comment]
Ikonky posunout víc doprava, aby byly pod výběrem jazyků.
