### ISSUE TITLE
Barvy ikon

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#12]
Přidat barevné ikonky služeb, aby se měnil každý button při najetí myší podle svojí barvy. 
@jaroslavaDvorakova má dodat ikonky?

**Comment by jirkadev** [comment]
chybí mi barva pro mapové sbírky

**Comment by LenkaKravecova** [comment]
No, vidíš.. Asi by to mělo být modré jako barva webu.

**Comment by jirkadev** [comment]
opraveno https://github.com/moravianlibrary/Rozcestnik-studovna/commit/507178d0c0458bb39455f7c4ab4a99ce76f8e83d
