### ISSUE TITLE
Změna buttonů Vstoupit

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#19]
LenkaD. dodá vysvětlující text k autorsky volná díla a všechna díla

**Comment by jirkadev** [comment]
Zatím jsem tam sám napsal text.

**Comment by LenkaKravecova** [comment]
Díky. Trochu jsem to upravila a upřesnila (byly tam nějaké chybky), zkopíruj tam, prosím, toto:

Volná díla
Jedná se o díla, na která se již nevztahují autorská a nakladatelská práva, např. uplynulo sedmdesát let od úmrtí autora nebo 50 let od vydání.

Všechna díla
Jedná se o díla autorsky chráněná i volná. Autorsky chráněná díla je možné prohlížet jen na počítačích MZK v prohlížeči autorsky chráněného obsahu.

Ještě bych nazvala ty dva režimy takto: 
Všechna díla
Pouze volná díla

Chceme jim naznačit, že režim všechna díla je to, co tam hledají - chráněná díla jsou důvod, proč jdou na kramerius do knihovny. Možná bych ten režim Všechna díla dala i první v pořadí.

**Comment by LenkaKravecova** [comment]
Co jsem psala, platí. Režimy určitě prohodit.

Dál prosíme změnit text v rámečku na "Zvolte přístup do digitální knihovny" a dali bychom to zeleně, tučně a do zeleného rámečku, aby to korespondovalo s ostatní zelenou.
