### ISSUE TITLE
Doplnění text tablety

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#21]
https://docs.google.com/presentation/d/1AYjKKcLRYY4xke5ZzHads_3oL4F885EvS5MqqqTDDm4/edit#slide=id.g120025b5a8_0_140

Upravili jsme text k tabletům, prosím doplnit.

**Comment by jirkadev** [comment]
Texty na všech stránkách nápovědy si můžete změnit sami, změna se projeví na webu za cca 15 minut. Návod je na hlavní stránce https://github.com/moravianlibrary/Rozcestnik-studovna

**Comment by JaroslavaDvorakova** [comment]
Jirko, záčátečník systomový knihovních návod moc nedává. Požádám Tě o vysvětlení a více podrobnější návod. V následujících dnech si za tebou zaskočím.

**Comment by LenkaKravecova** [comment]
Měli bychom se sejít a ozkoušet si to. Pak už to půjde dobře. Taky nám Jirka řekne, co všechno můžeme upravovat.

**Comment by jirkadev** [comment]
Dobře, teď jsem ten text doplnil
