### ISSUE TITLE
Co je v řešení (úkoly ostatní)

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#26]
Jája:
- anglický překlad-chybí aplikace
- sundat samolepky z monitorů-udělá služba

David:
- proklik z Krameria v nechráněném prohlížeči (spolupráce s @MartinRumanek)
- fakultativní úkol - logo Webarchiv

**Comment by LenkaKravecova** [comment]
úkoly stále platí

**Comment by jirkadev** [comment]
Linux #40
Ukládání dat #39 
proklik by měl fungovat https://github.com/moravianlibrary/Rozcestnik-studovna/commit/53dc0ef476f6fe9ee75518cf79add9c9fde74f88
