### ISSUE TITLE
Strana Jak hledat (Nápověda)

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#29]
Promyslet, jak graficky rozčlenit obsah strany (zelené nadpisy vypadají divně). Nějaký nápad, @jaroslavadvorakova ?

**Comment by jirkadev** [comment]
upravil jsem to, myslím, že je to OK

**Comment by JaroslavaDvorakova** [comment]
Jirko, můžeš mi ten tvůj slide též nasdílet?

**Comment by jirkadev** [comment]
Je to tohle, upravil jsem obrázky, a předělal trochu text, myslím, že to je celkem v pořádku http://vknihovne.mzk.cz/cs/jak-hledat
