### ISSUE TITLE
Název služby je Digitální knihovna MZK

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#3]
Služba se tak jmenuje. V návrhu je to záměrně. Přidat "MZK" do názvu sem: 

http://vknihovne.mzk.cz/cs (buton)
http://vknihovne.mzk.cz/cs/digitalni-knihovna
http://vknihovne.mzk.cz/cs/digitalni-knihovna-napoveda

**Comment by LenkaKravecova** [comment]
Sekci Digitální knihovna v menu nápovědy přejmenovat na Digitální knihovna MZK, jak je v návrhu.

**Comment by jirkadev** [comment]
opraveno
