### ISSUE TITLE
Uspořádání kapitol v nápovědě u Digitální knihovna MZK

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#30]
@jirikrepl Dávala jsem ti to na gitter, ale asi to zapadlo, takže tady je pořadí:

O digitální knihovně
Jak hledat
Jak tisknout
Půjčení tabletů
Mobilní aplikace Kramerius
Registrace a oblíbené

**Comment by jirkadev** [comment]
opraveno
