### ISSUE TITLE
Registrace - dopsat 2 věty

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#31]

**Comment by LenkaKravecova** [comment]
Prosím @jirikrepl o aplikování verze, kterou jsem vytvořila (Nápověda - registrace a oblíbené). Díky.

**Comment by LenkaKravecova** [comment]
Jej, teď se dívám, že se ten odkaz http://kramerius.mzk.cz otvírá ve stejném okně :/ To je taková prkotina, ale dokáže to vždycky otrávit, když to dělá. Šlo by to, prosím, otvírat v novém okně?

**Comment by jirkadev** [comment]
Vyřešeno, k vidění zde http://rozcestnik.openshift.mzk.cz/cs/registrace-a-oblibene
