### ISSUE TITLE
stránka: chráněný obsah

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#36]
Prohlížeč autorsky chráněného obsahu - zprovoznit, nechat tam dva základní buttony.
Adresa bude: vknihovne.mzk.cz/chraneny-obsah

**Comment by LenkaKravecova** [comment]
http://vknihovne.mzk.cz/cs/chraneny-obsah 
Nechci být hnidopich, ale ty buttony bych dala víc k sobě a pak dolů (vycentrovat na stránku).

**Comment by jirkadev** [comment]
opraveno: http://rozcestnik.openshift.mzk.cz/cs/chraneny-obsah
