### ISSUE TITLE
Automatická aktualizace stránek (Nápověda - úvod)

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#37]
Prosím znova nahrát změnu na vknihovne.mzk.cz u Nápověda - úvod

**Comment by jirkadev** [comment]
Vypnul jsem http://rozcestnik.mzk.cz/ rozcestník nyní beží v openshiftu, díky @dsecik zde: http://rozcestnik.openshift.mzk.cz/ změny na Githubu se projeví na webu do 20 minut @JaroslavaDvorakova @LenkaDamborska
