### ISSUE TITLE
Stránka: Digitální knihovna MZK

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#38]
Upravit text u slide Digitální knihovna MZK v prezentaci, nahrát do Githubu a poté aktualizovat na vknihovně.mzk.cz

**Comment by jirkadev** [comment]
text upraven: https://github.com/moravianlibrary/Rozcestnik-studovna/commit/d277f87e9e169d05f6d3832e5e3d89704aef6934 změny se projeví do 20 minut, viz #37
