### ISSUE TITLE
Odkaz na Digitální knihovnu MZK v nápovědě

### ISSUE THREAD

**Issue by LenkaKravecova** [moravianlibrary/Rozcestnik-studovna#4]
Otazník u butonu na hlavní stránce a i "Více o digitální knihovně" na http://vknihovne.mzk.cz/cs/digitalni-knihovna by měly odkazovat sem: http://vknihovne.mzk.cz/cs/digitalni-knihovna-napoveda
Díky.

**Comment by jirkadev** [comment]
opraveno
