### ISSUE TITLE
Stránka: Proč používáme Linux?

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#40]
Nový slide na Proč používáme Linux?

Jirko informace tahej z prezentace (https://docs.google.com/presentation/d/1AYjKKcLRYY4xke5ZzHads_3oL4F885EvS5MqqqTDDm4/edit#slide=id.g1015572402_2_23). O obrázky si řekni Davidovi.

**Comment by jirkadev** [comment]
Zatím jsme na stránku vložil text bez grafiky http://rozcestnik.openshift.mzk.cz/cs/linux
