### ISSUE TITLE
Používat title

### ISSUE THREAD

**Issue by davidvasicekmzk** [moravianlibrary/Rozcestnik-studovna#50]
Web nepoužívá v hlavičce html tag title, okna se pak pojmenovávají názvem prohlížeče. Na terminálech je spodní lišta dost nepřehledná, zvlášť pokud se pomocí rozcestníku otevře pacho - dole na liště je několik oken s názvem "Iceweasel" rozlišených jen malou ikonou.

Ideálně použít do titulku nadpis každé stránky + název webu, jak je to běžné (např. Digitální knihovna - vknihovne.mzk.cz). Anebo alespoň odlišit úvodní stránku pacha (titulek Prohlížeč autorsky chráněného obsahu) a zbytku webu (vknihovně.mzk.cz).

**Comment by jirkadev** [comment]
hotovo, všechny stránky mají svůj title, česká i anglická verze
