### ISSUE TITLE
Změna logo myQ

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#54]
Změnit logo na hlavní stránce menu (http://vknihovne.mzk.cz/cs) z safeQ na myQ. Nechat text "tiskové úlohy" a přidat logo myQ.

logo jsem zaslala do e-mailu.

**Comment by jirkadev** [comment]
Dobře díky, změněno na http://vknihovne.mzk.cz/cs.
