### ISSUE TITLE
font-změna

### ISSUE THREAD

**Issue by JaroslavaDvorakova** [moravianlibrary/Rozcestnik-studovna#8]
celý text změnit na DinPro (zaslala jsem na mail).

**Comment by jirkadev** [comment]
Je otázka jestli jaký použít. Kde jej použít (nadpisy, text). A jestli vůbec nějaký použít. Web MZK používá font arial.

**Comment by JaroslavaDvorakova** [comment]
Použij DinPro. David Ti zavolá ;).

**Comment by LenkaKravecova** [comment]
Když není k dispozici DIN Pro, prosím nadefinuj v css alternativní písmo, asi takto:
font-family: DINPro, Arial,sans-serif;
